version: "3.9"
volumes:
  postgres_data: 

services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./1_tables.sql:/docker-entrypoint-initdb.d/1_tables.sql:ro
      - postgres_data:/var/lib/postgresql/data

  backend:
    hostname: backend
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
